### ISSUE TITLE
GazeManager.FocusedObject as static variable

### ISSUE THREAD

**Issue by yosun** [Microsoft/HoloToolkit-Unity#110]
is there a case where GazeManager.FocusedObject might vary - i.e., would there be multiple gaze cursors in a single scene? 

namely, why isn't FocusedObject a static variable - when would it need to be accessed as an instance (and multiple instances)?

**Comment by jwittner** [comment]
GazeManager follows the Singleton paradigm rather than the static class one. For this reason the Focused object is relative to the GazeManager object. To note, for better or worse the HoloToolkit-Unity Singleton class chooses the first available Instance, but doesn't prevent multiple instances from existing. There are many arguments for the current implementation, a key one is to allow the GazeManager to vary across scenes. After placing an instance of the GazeManager into the scene, from script you can do GazeManager.Instance.ForcusedObject and get very similar behavior.
