### ISSUE TITLE
SessionManager.UI Throws Error code 5 on port 20605

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit-Unity#206]
SessionManager.UI Throws Error code 5 on port 20605.

Tested this on 3 different machines w/firewalls turned off.

**Comment by NeerajW** [comment]
I believe the sharing code uses a range of port numbers 20346-20602.

**Comment by HodgsonSDAS** [comment]
Shouldn't this just work right out of the box?

Also, I'm not sure where I should be changing the port number.

**Comment by NeerajW** [comment]
@alexdrenea any ideas?

**Comment by alexdrenea** [comment]
This is normal / expected. 
Port 20605 is used for the auto-discovery mechanism. Every component of the HoloToolkit sharing platform (client, server, session manager) will try to open a socket on port 20605 to listen for discovery requests by others. The port is "hardcoded" and is required to be a fixed port so that it can be easy to send a broadcast on the network.
When you run 2 or more components on the same machine (in your case, server and manager) both will try to open that connection on 20605 and obviously the second one will fail since the port is already in use. 

This is normally not a problem for 2 reasons. Even if the port opening fails, that does not affect the sharing functionality since this is an extra feature and not critical to the system. Even then, in most cases, you only need to find the server via auto-discovery and not other components so as long as you open the server first others will be able to find it and there won't be any issues.

I've mentioned this in a post on the HoloLens forums  as well - https://forums.hololens.com/discussion/comment/7653#Comment_7653

I am thinking maybe we could update the readme to make it a bit clearer?
@NeerajW  do you want me to try and come up with an initial draft ?

**Comment by HodgsonSDAS** [comment]
Okay, that makes a lot more sense.  I remember reading your comment on the forum, but didn't quite understand until you explained it here.

In either case, I don't think throwing an error code should be "normal / expected".  Should we be handling this better?

**Comment by alexdrenea** [comment]
Not sure about handling it better. After all it **is** a legit error - the application cannot open a connection. just that in our case, we ourselves via another application from the same platform are blocking it for a legit reason.
There might be cases where some other random process is blocking the port and then you need to know about that.

I think the best we could do is (if possible) change the error message to be more descriptive and potentially update the documentation.

**Comment by HodgsonSDAS** [comment]
Maybe there's a way to know if another application has already initiated the auto discovery on that port, and prevent the attempt to connect?

I'd look through the source myself, but my company policy does not allow me to contribute code/work to open source projects.

**Comment by NeerajW** [comment]
@alexdrenea it seems worth looking into @HodgsonSDAS's suggestion. What do you think?

**Comment by alexdrenea** [comment]
Ah, I replied that day but my connection was unstable and apparently it didn't actually submit.

> and keep that functionality to legitimate errors, and prevent the error from being thrown in cases where we already have an application on the port.

Like I said, the error is a legitimate error, and is only thrown if an application is blocking the port, regardless if that application is from the toolkit (client, manager, server) or not.

> If this is true, then we should be able to know if an app is already using it if we send a request to connect before we open a socket on that port.

That is true, but there's no **easy** way of knowing if the other app is part of the toolkit or not. Any app can block the port and we must ensure we let the user know that there's an issue.

**Comment by HodgsonSDAS** [comment]
> That is true, but there's no easy way of knowing if the other app is part of the toolkit or not.

@alexdrenea Would this be much different than the AutoDiscovery in the SharingStage.cs up date you did?

For Example:
If we've auto discovered a server and connected to it, don't try to connect to port 20605

**Comment by alexdrenea** [comment]
:) that's exactly what I was thinking when I said it's not _easy_ .
Essentially, when you open the SessionManager or the Client, you can run an AutoDiscovery to see if there's a reply with your own IP. In which case, you don't attempt to open that port yourself.

However, I am still not satisfied that this is a good solution. 
First of all, it will cause the component to start slower (or at least, its AutoDiscovery service will start slower since it has to wait for responses before it attempts to open the port). 
Second, for the server component in particular, I think this is a bad idea, since it's crucial for the server to have the feature enabled and the user should know if it's not working no matter who's blocking the port.
Finally, let's look at the actual problem that we are trying to solve here? From my point of view it's a simple, expected error that in most cases won't even reproduce, and when it does it doesn't affect any functionality.

If there was a simple fix, I would be all for it but I don't think the current solution is overly complicated for what benefit it brings.

**Comment by jwittner** [comment]
Can we catch the exception and improve the error message?

**Comment by alexdrenea** [comment]
Starting from the error itself ...
> SharingService [...\holotoolkit\sharing\src\source\common\private\xsocketmanagerimpl.cpp (668)]: Failed to create incoming connection on port 20605.  Error code: 5

I found the code that generates the message:

```
	// Startup the peer interface with the given socket settings.  Will fail if we already have a peer interface for this host
	RakNet::StartupResult startupResult = RakNet::STARTUP_OTHER_FAILURE;

	try
	{
		startupResult = peerConnection->m_peer->Startup(discoveryCommand->GetMaxConnections(), &socketDescriptor, 1);
	}
	catch (...) {}

	if (startupResult != RakNet::RAKNET_STARTED)
	{
		LogError("Failed to create incoming connection on port %u.  Error code: %u", discoveryCommand->GetPort(), startupResult);
		return;
	}
```

By the looks of it it's actually handling the case quite nicely and based on the comment itself it seems that whoever wrote it was thinking exactly in the lines of our conversation here.

The code itself seems to be shared by both the server and the manager and it's not straight up clear how it gets called (or at least I can't figure it out without digging deeper). So at this point I personaly, will stay way from changing anything other than the string message because I don't know what and in what way will the changes affect the overall system.

If anyone wants to take a stab at whatever other change, I can help with an extra eye (ok, 2 extra eyes) in the review phase.

P.S. anyone know if it's possible to reference the file and code itself from the repo rather than copy paste? - same how you do in the code review?

**Comment by jwittner** [comment]
> anyone know if it's possible to reference the file and code itself from the repo rather than copy paste? - same how you do in the code review?

Far as I can tell you can get links by selecting from the code on the left (yellow highlight a section), then your URL will update like this:
https://github.com/Microsoft/HoloToolkit/blob/master/Sharing/Src/Source/Common/Private/XSocketManagerImpl.cpp#L666-L670

Doesn't embed the text though. =(

**Comment by HodgsonSDAS** [comment]
Hmm, well considering I'm still having issues just getting the HoloToolkit solution to even open/build on my machine, I'm not too much help actually looking at the code except though github.

I did a quick test and started the Session List Manager UI _before_ the Sharing Service Server.
I noticed that the Session Manager UI will automatically connect to the Sharing Service and create a default session.

Why do we need/want the Session List Manager UI to create a auto discovery connection on that port when it starts up, if we assume people will always start the Sharing Services first?  Shouldn't this ideally only be handled by the Server anyway?

Is there a way to get the Session List Manager UI to attempt to connect to the sharing service server before we try to process the discover response command?  And if we successfully get the session server, not attempt the connection to the auto discovery port?

**Comment by HodgsonSDAS** [comment]
I'm going to close this issue and open it in the main HoloToolKit

**Comment by dtmnash** [comment]
I just ran into this same issue. What i don't understand, if two apps from the same machine can't join the same session, is how the Session Manager UI app is able to join from the same machine without a problem. 

In our case we are building a Unity2D app and a Unity3D app (HoloLens) that needs to send messages back and forth. The 2D app is just responsible for controlling the experience of the HoloLens app. Switch scenes, enable/disable GOs, etc. 

Running them together on the same machine in development produces the error above.
