### ISSUE TITLE
The Configure Menu don't check Unity C# Project Option.

### ISSUE THREAD

**Issue by zwxbest** [Microsoft/HoloToolkit-Unity#239]
Apply Hololens Project Settings will not check Unity C# Project Option.

**Comment by NeerajW** [comment]
@zwxbest would you like to make the change and issue a pull request?

**Comment by jwittner** [comment]
This option is up to the developer and isn't a part of the recommended setup for Unity that the Project settings apply: https://developer.microsoft.com/en-us/windows/holographic/unity_development_overview

There is an issue here: https://github.com/Microsoft/HoloToolkit-Unity/issues/203 where we decided to put this option in the HoloToolkit/Build Window so that it's easier to remember your setting.
