### ISSUE TITLE
Redundant/duplicated code to set OverrideFocusedObject/FocusedObject

### ISSUE THREAD

**Issue by briggySmalls** [Microsoft/HoloToolkit-Unity#273]
[Assignment of _OverrideFocusedObject_ in _GestureManager_](https://github.com/Microsoft/HoloToolkit-Unity/blob/c014337c6821e836d9268bd72015086dd582aada/Assets/HoloToolkit/Input/Scripts/GestureManager.cs#L251) duplicates [assignment of _FocusedObject_ in _GazeManager_](https://github.com/Microsoft/HoloToolkit-Unity/blob/c014337c6821e836d9268bd72015086dd582aada/Assets/HoloToolkit/Input/Scripts/GazeManager.cs#L138).

Given _GestureManager_ explicitly requires _GazeManager_, shouldn't the _GestureManager_ simply use the _FocusedObject_ property on the _GazeManager_ to update _OverrideFocusedObject_?

**Comment by HodgsonSDAS** [comment]
I think part of the thinking was that people could explicitly set a override object if they really needed to outside of both gaze and gesture managers.

The `FocusedObject` in the gaze manager doesn't necessarily get overridden, because you could potentially have a null `FocusedObject` in the gaze manager, but still have a `FocusedObject` in the gesture manager if you specify an override.

This enables people to be able to still use a gesture on a hologram that people are not currently gazing at.

**Comment by NeerajW** [comment]
@briggySmalls please close when you are ready. @HodgsonSDAS described it perfectly.

**Comment by briggySmalls** [comment]
Thanks for the explaination.
