### ISSUE TITLE
SurfacePlane doesn't function if placed in the editor.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit-Unity#34]
The plane is never assigned to and the surface data is never built.

**Comment by angelaHillier** [comment]
SurfacePlane is a helper object that works with the SurfaceToPlanes script. It is not a stand-alone component. The plane/surface data is filled in by SurfaceToPlanes after the planes have been generated.

**Comment by angelaHillier** [comment]
Be sure to check out the SpatialProcessing test scene in the HoloToolkit. This shows how SurfacePlane was originally intended to be used (as a referenced prefab on SurfaceToPlanes). If you do make SurfacePlane.cs a stand-alone component, then please make sure that you do not regress functionality of this test scene, since we rely on this in our spatial mapping course. Thanks!

**Comment by angelaHillier** [comment]
Looked at your change, and it's fine. Merged the code into main.

**Comment by jwittner** [comment]
Thanks for checking everything out. We're using the SpatialMeshesToPlanes pretty extensively, but testing was difficult without functionality in the editor. Glad the fixes were simple. =)

**Comment by jwittner** [comment]
Resolved by #35
