### ISSUE TITLE
KeywordManager:  NullReferenceException in Update() when initialization fails.

### ISSUE THREAD

**Issue by aalmada** [Microsoft/HoloToolkit-Unity#396]
KeywordManager doesn't check if keywordRecognizer is null in Update(), resulting in an exception thrown on every loop cycle. Initialization can fail in two cases; an empty KeywordsAndResponses or it contains duplicate keywords.

Actually I don't think Update() needs to check if keywordRecognizer.IsRunning. The recognizer should be always running if this behavior is enabled (#359). Update() is not called when this behavior is disabled. One less 'if' in Update() is good for performance.

Still, duplicate keywords should not throw an exception but log an error message.

**Comment by keveleigh** [comment]
The fix should just be to check if keywordRecognizer != null in update before checking IsRunning. This check was a recent addition because you should typically call Start/StopRecognizer() to control recognition, which leaves the script enabled.

The addition of a duplicate keywords check is good too.

**Comment by aalmada** [comment]
@keveleigh You're right. I missed the Start/StopRecognizer() paths. I'll fix it in the #398

**Comment by keveleigh** [comment]
Fixed via #398
