### ISSUE TITLE
IManipulationHandler to rotate object and use in Unity Editor

### ISSUE THREAD

**Issue by GKersten** [Microsoft/HoloToolkit-Unity#448]
I am trying to use the IManipulationHandler to rotate a Sphere. I'd like to test this in Unity Editor, but I cannot seem to get this working by holding the click and move. Am I missing something or is this not implemented? The methods are called correctly when running on the HoloLens.

Also, did anyone already implement rotation of objects by using the IManipulationHandler?

**Comment by GKersten** [comment]
For anyone else searching for this, rotating an object is quite easy with the IManipulationHandler:

    public void OnManipulationUpdated(ManipulationEventData eventData)
    {
        float speed = 25f;
        var rotation = new Vector3(-eventData.CumulativeDelta.y, -eventData.CumulativeDelta.x);
        transform.Rotate(rotation * speed, Space.World);
    }

Still wondering how to interact with it in Unity Editor.

**Comment by GKersten** [comment]
That's correct, I can see the small blue hand indicator moving, tried both left and right hand (with space bar). But I can not seem to trigger the events for the manipulationhandler when clicking, although I can see the cursor animating.

**Comment by HodgsonSDAS** [comment]
Make sure your scene is [set up properly](https://github.com/HodgsonSDAS/HoloToolkit-Unity/blob/HTK-local/GettingStarted.md#3-preparing-a-scene-for-holographic-content) and take a look at [HandDraggable.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs)

**Comment by GKersten** [comment]
Scene is setup correctly, prove is that I get it successfully working on the HoloLens itself, problem is only related to Unity Editor.

The HandDraggable has it's own implementation, using the InputHandler directly which successfully calls the events when running in the Unity Editor.

**Comment by islacoder** [comment]
I have the same issue and it applies to INavigationHandler as well.  I cannot get Unity Editor to work with manipulation and navigation using those interfaces.  HandDraggable.cs doesn't use those interfaces.

**Comment by S-Hodgson-MMOARgames** [comment]
I understand that HandDraggable doesn't use those interfaces, but I thought it would provide a good example of an implementation that could solve the problem.

**Comment by HodgsonSDAS** [comment]
After more investigation the only two options are to calculate the delta of your hand movement in the editor or to update the EditorHandsInput to handle the navigation and manipulation events properly.

**Comment by maxouellet** [comment]
All the editor input stuff is faked by the EditorHandsInput input source. This input source currently provides fake hand states, positions and airtaps,, but does not implement the Windows gestures such as Navigation and Manipulation.

If we wanted to support them, we'd have to update EditorHandsInput so that it properly fakes them, as @HodgsonSDAS suggested. Or it could be a new EditorGesturesInput whose role it is to fake gestures. The reason I didn't do it initially is because I didn't have the time to write a proper fake implementation for them. It shouldn't be too hard to do though.

FWIW, I have successfully used the manipulation gesture to move and rotate objects in some prototypes. It works relatively well, with the upside that it makes it easier to differentiate between a tap and a tap + drag. The only downside is that the refresh rate on these events is a little lower than the raw hands input: as long as you smooth the input, it should still work fine.

**Comment by barmyard** [comment]
I second this.

Another problem which is related is that HandDraggable has its own implementation.
I assigned a Fallback ManipulationHandler to my scene, but if I do a manipulation gesture on a gameObject that also has HandDraggable attached, both events are triggered.

If HandDraggable would implement the proper ManipulationHandler, I think this issue should be fixed.
I'll see what I can do, but I can't promise anything now.

**Comment by maxouellet** [comment]
We've internally implemented the manipulation and hold gestures to EditorHandsInput. The code is relatively simple, but I've been pretty busy over the last few weeks, so not sure when I can bring this back... I can try to find some time this week or next week, but no guarantee :(

HandDraggable has its own implementation because it relies on the frame-by-frame updated position provided by the polling APIs (in RawInteractionsSourcesInput). You could use the manipulation gesture for this, but it has a few caveats:

- It doesn't give you the hand position (only a delta). So you still need to somehow get the hand position in order to use the exact same logic that is in HandDraggable
- Its refresh rate (on ManipulationUpdated) is relatively low (not each frame), so the ensuing manipulation stutters if you don't stabilize it through interpolation

**Comment by basuarya** [comment]
@GKersten Can you pleas elaborate how did you use IManipulationHandler to rotate gameobject?
Thanks.

**Comment by jessemcculloch** [comment]
Before I file a new issue, is this what is also keeping the IHoldHandler events from firing?

**Comment by maxouellet** [comment]
Yeah, Hold is not currently implemented in the EditorHandsInput that is in HoloToolkit.

I'm really swamped right now, so I sadly don't have the time to validate this fix across all of HoloToolkit, but I've attached the EditorHandsInput.cs file that I am using locally. It adds supports for hold and manipulation. I haven't looked to see if this will compile as-is in the current state of HoloToolkit, but if not, it should be very close to what you need.

If someone wants to take it upon themselves to validate and submit it, feel free to do so :) Hope this helps!

[EditorHandsInput.zip](https://github.com/Microsoft/HoloToolkit-Unity/files/794796/EditorHandsInput.zip)

**Comment by HodgsonSDAS** [comment]
I'd take a look, but can't download zips at work 😦

**Comment by StephenHodgson** [comment]
Hey Max, looked this over. Seems to be upset about a missing reference to `InputSourceEventArgs`.

**Comment by maxouellet** [comment]
@StephenHodgson Not surprising, I think that's because that class has now been removed in HoloToolkit following a change by @aalmada . Now instead of creating that event args, you just call inputManager.Raise* , where the wildcard is replaced by the type of event you want to raise.

**Comment by StephenHodgson** [comment]
Ahh, then that should be easy to fix.  Thanks

**Comment by StephenHodgson** [comment]
@GKersten please test out this PR so we know it works well for your purposes.

**Comment by nipundavid** [comment]
OnManipulationUpdated only works when focus is on the gameobject, if the focus is lost it just stop working not even go to OnManipulationCanceled

**Comment by maxouellet** [comment]
@nipundavid You can add yourself as a modal input handler at OnManipulationStarted to get the follow-up events. I think that's what HandDraggable does, and what we've been doing in our various multi-frame interactions

**Comment by jsmith09** [comment]
@StephenHodgson I am little confused on how to test IManipulationHandler now in Unity Editor. Has the issue been fixed? If so, what are the instructions to setup Unity Editor for IManipulationHandler?
