### ISSUE TITLE
3DTextPrefab and samples report missing font

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/HoloToolkit-Unity#470]
3DTextPrefab and samples report missing font and don't shows texts, just outlines. Which is kind of confusing. Why is the font described https://github.com/Microsoft/HoloToolkit-Unity/blob/master/External/ReadMeImages/TextPrefabInstructions02.png not included? Copyright reasons?

**Comment by cre8ivepark** [comment]
Hi @LocalJoost Yes, because of the font file copyright/license, we cannot distribute Segoe UI font file through GitHub. Please follow the instructions in this [Readme file ](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/UI/README.md)for importing the Segoe UI font file from your Windows/Font folder. Thanks!

**Comment by LocalJoost** [comment]
Thanks for the explanation. Dunny if there is a free font you could use (and reship) instead.

**Comment by HodgsonSDAS** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/pull/425
