### ISSUE TITLE
add Cursor,Directional indicator,Navigation and Manipulation Input

### ISSUE THREAD

**Issue by lycheeyy** [Microsoft/HoloToolkit-Unity#502]
Hello,
I'm very new in unity, I just got the HoloLens. It’s amazing!! I already impoted holotoolkit(1.5.5.0) to assets folder. And I’m following the academy tutorial. Everything is alright and I can get the same effect like in the tutorial with the files that provided in the beginning of the tutorial. But when I created my new project, I got confused. As follow the tutorial as before, I cannot find a lot of assets inside the holotoolkit, like”Cursor Manager”script,”Directional Indicator”asset “Gesture Manager”,”Gesture Action”,etc. And when I try to import the missing staff from the files of academy tutorial, there’s always some error. So what is my problem and how to add Cursor,Directional indicator,Navigation and Manipulation Input to a new project? 
Thanks a lot!!!

**Comment by S-Hodgson-MMOARgames** [comment]
The HoloAcademy and HoloToolkit are not the same.
There's actually a [repository dedicated for the HoloAcademy](https://github.com/Microsoft/HolographicAcademy).

**Comment by lycheeyy** [comment]
@S-Hodgson-MMOARgames 
Thanks for replying me. I already learned all the academy tutorials and got good result. Then I installed the **latest holotoolkit** and want to build my own project. My task is very basic and simple, I got a solidworks assembly, the effect what I need is, I can see the assembly hologram and interact with it, like move, rotate, explode the parts, etc in my hololens. Now I already transferred the assembly inside unity, but I don't know how to add gaze and gesture input to it. I stuck here for almost one week. The most important thing I want to know is, **without** "cursor manager" "gesture manager" and a lot of other scripts and assets in the **latest holotoolkit**, how can I add the gaze and gesture input to the assembly? Do I need to write the C# script myself? 
Thank you!

**Comment by sberhorst** [comment]
@S-Hodgson-MMOARgames 
I can appreciate what @lycheeyy is saying as I am also new to Holo development.  Super great stuff, and the Academy was really straight forward.  A robot could have executed the steps as they were all prepackage, and ready to go.  It led to great quick and dirty to get into Holo Development, but as we now continue to take the next step and use the HoloAcademy as a starting point, it doesn't allow for usage of the cool stuff you guys have been doing with this HoloToolkit repo.  Unfortunately, the leap from the Academy to this is larger than new people like myself can bridge, as we are using the concepts in the Academy to do our own stuff, so when we start to use concepts like Hologram Placement scripts...taking from the Holo Academy will fail given they call other assets not within our current new model.  This is were we are falling down as we take advantage of the latest and greatest.  As I spend most of my time copy/paste for scripting...and just changing a parameter here and there....apparently not working.  Also not a great coder, but more of a visual builder.

**Comment by lycheeyy** [comment]
@sberhorst yes, copy and paste. 
As the very beginner, follow the academy is the best way to learn, but after this, just get confused. There's no information about how to build a new project without the files that provided by the academy tutorial.

**Comment by sberhorst** [comment]
@lycheeyy 
I found that https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md did a nice job in getting the environment set up the correct way.  These guys have done a fantastic job of GUI driven setup for a Holo environment.  The problem exists for you here because the scripts used in the HoloAcademy do not reside in in the same manner, and some just don't exist at all, so you CAN'T use the scripts from the 240 lab.  You need to use the ones provided here in order to replicate the same "experience", as copy/paste will result in massive errors as references and dependencies are broken.  Hopefully, @S-Hodgson-MMOARgames can provide us with some help, because he's awesome.  :)

**Comment by S-Hodgson-MMOARgames** [comment]
@lycheeyy @sberhorst , I encourage you guys to take a look at each scene in each of the test folders. They pretty much demonstrate how to use each of the components.

I've really been trying to get the documentation up to speed, but when it comes down to it, you're really just going to need to read the code and get your hands dirty trying stuff out.

If you want help I charge by the hour 💸 or 🍺 haha.

**Comment by S-Hodgson-MMOARgames** [comment]
@lycheeyy 
>The most important thing I want to know is, without "cursor manager" "gesture manager" and a lot of other scripts and assets in the latest holotoolkit, how can I add the gaze and gesture input to the assembly? Do I need to write the C# script myself?

For getting simple input working like a tap or gesture you will need to write your own script that will handle the right kinds of inputs for you. Specifically you're going to want to write a class that's similar to [TapResponder.cs](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/README.md#taprespondercs)

Pretty much any input script you write will implement one of the input handlers described in the [Input Overview](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/README.md#input-module-design).

**Comment by NeerajW** [comment]
@lycheeyy  and @sberhorst completely appreciate and understand the problem you are having. And thank you giving another data point. This is a very typical issue with OSS and non-OSS components :) Academy is designed exactly for folks like you who are beginners and may or may not have experience with Unity or C# development. As HoloToolkit is OSS it grows as the developers using it grow. So it can be very hard to keep academy simple and in step with toolkit. Hence they diverge in content as time goes by. To make the bridge simpler from academy to toolkit here's what we are trying to to:

1. You can have your academy project and import the latest HoloToolkit unity package and they should work for the most part since we use different namespaces. But still this is not error prone.
2. In the toolkit packages, look at test scenes for help. They are great at showing how to do stuff.
3. For simple Gaze and Gesture: https://github.com/Microsoft/HoloToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Tests/Scenes/InputTapTest.unity
4. You will also find Direction Indicator scripts in the Utilities folder.

Hope this helps!!

**Comment by thebanjomatic** [comment]
@NeerajW would it make sense to change the name of the toolkit that's part of the Academy tutorials ? It seems to me if it was called "HolographicAcademyToolkit" or something similar throughout the academy it wouldn't be as surprising that the code is divergent.

**Comment by HodgsonSDAS** [comment]
@thebanjomatic that's a good point. Do they currently share the same namespaces?

**Comment by thebanjomatic** [comment]
@HodgsonSDAS I only checked Holograms 210, but scripts have the namespace as: `Academy.HoloToolkit.Unity`, and they sit inside of the `Assets/HoloToolkit-Gaze-210` folder, so there aren't any collisions.  

I guess its already spelled out a little bit that its a specific fork of the holotoolkit, but I do think the right choice of name could make things more clear. I just don't know what that name would be.

**Comment by lycheeyy** [comment]
@NeerajW  @S-Hodgson-MMOARgames It works!!!Thank you! I can see the cursor on and off my assembly!
I still have problem with gestures. Now I can use gaze and see the cursor. I can move the assembly using "Hand Draggable"script. I can use "HeadsupDirectionIndicator" as you told me in Utilities folder. But I can't get the same effect like in academy 210 and 211:
1,”Interactible(choose different part of assembly)”
2,”Navigation(rotate assembly in every direction, not only Y-direction)”
3,”Model expansion(expand the every part of assembly)”.
Thank you!
