### ISSUE TITLE
Is there a way to "Suspend" a World Anchor?

### ISSUE THREAD

**Issue by jasonhbartlett** [Microsoft/HoloToolkit-Unity#538]
My app uses Vuforia AR . Vuforia AR has it's own camera and spatial coordinate system.  Objects apparently move back and forth between the Vuforia AR coordinate system and Hololens coordinate system.
So I have a  Vuforia image target (or tag) for reliable physical positioning of holograms.  However I want the user to be able to re-position the holograms for tweaking exact placement relative to the image target.  When the user clicks a "modify" button, I simply un-parent the objects from the image target and attach the World Anchor.  This moves the holograms fully into the Hololens coordinate system.  And attaching the world anchor is what is critical to having the position persist between app cycles.

When the user clicks the "stop modify" button, I set the object parentage back to the image target, moving it back into the Vuforia AR coordinate system, and unfortunately I have to remove the world anchor.  Leaving the world anchor attached causes havoc with the Vuforia AR positioning so the hologram does not stick to the image target any longer.

Everything is working great while the app is running.  I can re-position the holograms and then that stays changed and will stick to the image target for the life of the app.  But I want it to stay changed between app cycles.

I did not see any method for disabling the world anchor.
I'm trying to use OnApplicationQuit to simply un-parent and attach the world anchor right before app closes, but so far that doesn't seem to be working.  Perhaps I need to look into Vuforia API's to see if they have something comparable to the persistent world anchor that Windows Holographic has.

Otherwise, I wanted to check with you guys to see if you had any ideas.  I was thinking of perhaps a suspend method for the world anchor so that I could turn it off without removing it from the anchor store.

**Comment by StephenHodgson** [comment]
I wouldn't say this is a HoloToolkit specific question, but rather a general Unity HoloLens platform one.

First check out the documentation on world anchors from both [Unity](https://docs.unity3d.com/ScriptReference/VR.WSA.WorldAnchor.html)  and [Microsoft](https://developer.microsoft.com/en-us/windows/holographic/world_anchor_in_unity#removing_a_world_anchor)

Essentially you'd need to remove the `WorldAnchor` component using

```
Destroy(gameObject.GetComponent<WorldAnchor>());
```

When you want to attach your new anchor, you'd just want to add a new `WorldAnchor` component to the game object you're wanting to anchor.
```
AddComponent<WorldAnchor>();
```

Using the HoloToolkit `WorldAnchorManager` might make things a bit easier.  It pretty much wraps the `WorldAnchorStore` and `Persistance` APIs to make things a bit more streamlined. Keep in mind this class can only be called/utilized on device not through the editor because it depends on `UnityEngine.VR.WSA`.

TapToPlace.cs utilized the `WorldAnchorManager` and shows some examples of its usage:
```
WorldAnchorManager.AttachAnchor(gameObject, SavedAnchorFriendlyName);
WorldAnchorManager.RemoveAnchor(gameObject);
```

**Comment by StephenHodgson** [comment]
@jasonhbartlett was this answer helpful?

**Comment by jasonhbartlett** [comment]
Sorry for not responding much sooner. My resolution was to save the objects coordinate information to the local file system using JSON files and a serialized list.  This was necessary because when the app closed, these objects were children of the Vuforia image target and therefore part of the Vuforia spatial coordinate system - the objects position being relative to the parent image target.  That worked out just fine.
Yeah this wasn't really a HTK issue.  I will close this out.  Thanks!
