### ISSUE TITLE
exporting the holotoolkit example to windows store (UWP) gives error

### ISSUE THREAD

**Issue by tipking** [Microsoft/HoloToolkit-Unity#615]
When i try to run the holotoolkit example and export to windows store (UWP) i get the following error.

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(142,45): error CS0246: The type or namespace name 'IAsyncAction' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(142,69): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(184,37): error CS0246: The type or namespace name 'IAsyncOperation<>' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(184,70): error CS0246: The type or namespace name 'AsyncStatus' could not be found (are you missing a using directive or an assembly reference?)

Assets\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\RemoteMeshSource.cs(33,17): error CS0246: The type or namespace name 'StreamSocket' could not be found (are you missing a using directive or an assembly reference?)

and in 

#if !UNITY_EDITOR && UNITY_METRO 
using System.Collections.Generic;
using Windows.Networking.Sockets;
using Windows.Storage.Streams;
using Windows.Networking;
using Windows.Foundation;
#endif

if I comment the #if and #endif I get the following error
Error	CS0246	The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)

**Comment by StephenHodgson** [comment]
Which example scene?

**Comment by ThmsMsqrt** [comment]
Hi, I was getting the same kind of errors today while trying to build some scenes (I was using Unity v5.1.1f1 + HTK-Unity v1.5.5). So far everything worked well last until Friday (last time I built something). But after updating VS 2017 to the [latest release](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.1.26403.03), I started to have build problems. So I updated Unity to 5.6.0f3 and cloned the HTK-Unity repository again. I tried to run some scenes, got the errors referenced and fixed in [#614](https://github.com/Microsoft/HoloToolkit-Unity/pull/614). After applying the changes, it fixed all the problems at the end, and it seems everything is building correctly now.

**Comment by StephenHodgson** [comment]
I've also been having issues building in VS2017, I suggest keeping to 2015

**Comment by tipking** [comment]
@StephenHodgson - color picker example.
@ThmsMsqrt - thanx for the explanation
I installed 2017 then removed it but still the error exists

**Comment by StephenHodgson** [comment]
Thanks, I'll take a look at it later this evening.

**Comment by ThmsMsqrt** [comment]
@tipking You are welcome. I was actually trying with the Color Picker example too and I got it working with the changes I explained.
