### ISSUE TITLE
Unity hololens using holotoolkit FOV always 16.97196

### ISSUE THREAD

**Issue by tipking** [Microsoft/HoloToolkit-Unity#634]
I am using unity with holotoolkit for developing app for hololens. The issue is the Field of View (FOV) of the main camera is always 16.97196 no matter what values is input. I even added a script to deliberately set the FOV value to 60 but it resets to 16.97196. Can the FOV value be set the user requirements. 
![fov](https://cloud.githubusercontent.com/assets/2418256/25263536/095b2ec6-267e-11e7-9070-610486fe2288.png)

**Comment by KoenvanderBorght** [comment]
Isn't that because of the limited FoV from a hardware perspective?

**Comment by tipking** [comment]
Thanks for the reply. The reason why i want to change FOV because I need to play 360 video in a sphere. The video looks very close and not able to get the desired result. The standard FOV for 360 sphere is 60

**Comment by StephenHodgson** [comment]
@tipking, I don't think there's a way to change this, because it's hardware dependent.

**Comment by thebanjomatic** [comment]
As a side-note, scaling the sphere up shouldn't actually display more video content because the FOV angle is independent of the radius. It will, however, make it look further away if you are using a monoscopic video.

So if it looks close to your face then a larger radius will make things feel more natural, but if the issue is the amount of content you can see at once, that is bound to the hardware field of view.

**Comment by keveleigh** [comment]
This seems resolved. That value comes from the device, so changing it doesn't mean anything to the hardware.
